os: linux

language: r
sudo: required
apt_packages:
  - pdf2djvu

script:
  - pdflatex -interaction=nonstopmode CV_Montel.tex
  - pdf2djvu -d 1200 -o CV_Montel.djvu CV_Montel.pdf
after_success:

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: 
    - "CV_Montel.pdf"
    - "CV_Montel.djvu"
  skip_cleanup: true
  on:
    tags: true
    repo: moutonjr/CV_LaTeX

